# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

app:
  dbHost: postgres13
  dbName: push

image:
  repository: sr2020/push
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80
