language: node_js
node_js:
  - "8"

jobs:
  include:
    - stage: build and push docker image
      before_script:
        - yarn
        - yarn global add typescript@3.5.1
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        # - yarn --cwd=packages/billing test
        - make build
        - make push

    - stage: deploy production
      script:
        - make deploy server=35.234.112.65 password=$USER_PASSWORD

addons:
  ssh_known_hosts:
    - 35.234.112.65
  apt:
    packages:
      - sshpass
      - sox
