language: node_js
node_js:
  - '8'

jobs:
  include:
    - stage: run tests
      before_script:
        - npm i -g yarn@1.13.0
        - yarn
      script:
        - yarn --cwd=packages/billing test
        - yarn --cwd=packages/push test

    - stage: build and push docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make build
        - make push

    - stage: deploy production
      script:
        - make deploy server=35.234.112.65 password=$USER_PASSWORD

addons:
  ssh_known_hosts:
    - 35.234.112.65
  apt:
    packages:
      - sshpass
      - sox
