language: node_js
node_js:
  - '10'

jobs:
  include:
    - stage: run tests
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
        - export PATH=$HOME/.yarn/bin:$PATH
      script:
        - lerna run build
        - lerna run test -- --forbid-only
        - lerna run lint

    - stage: build and push docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - lerna run docker:build
        - lerna run docker:push

    - stage: deploy production
      script:
        - make deploy server=35.234.112.65 password=$USER_PASSWORD

addons:
  ssh_known_hosts:
    - 35.234.112.65
  apt:
    packages:
      - sshpass
      - sox
