language: node_js
node_js:
  - '10'
cache: yarn

jobs:
  include:
    - stage: build & run tests & lint
      name: tests
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
        - export PATH=$HOME/.yarn/bin:$PATH
      script:
        - lerna run coverage:test --concurrency=1 --stream -- --forbid-only
      after_success:
        - lerna run coverage:merge
        - yarn run coverage:coveralls
        - yarn run coverage:codecov
    - name: lint
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
        - export PATH=$HOME/.yarn/bin:$PATH
      script:
        - lerna run lint
    - name: build
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
        - export PATH=$HOME/.yarn/bin:$PATH
      script:
        - lerna run build
    - stage: build and push docker image
      install: 'true'
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - lerna run docker:build --scope billing && lerna run docker:push --scope billing
    - install: 'true'
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - lerna run docker:build --scope models-manager && lerna run docker:push --scope models-manager
    - install: 'true'
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - lerna run docker:build --scope push && lerna run docker:push --scope push
    - install: 'true'
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - lerna run docker:build --scope sr2020-models && lerna run docker:push --scope sr2020-models

    - stage: deploy production
      install: 'true'
      script:
        - make deploy server=instance.evarun.ru password=$USER_PASSWORD

addons:
  ssh_known_hosts:
    - instance.evarun.ru
  apt:
    packages:
      - sshpass
      - sox
