apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: models-manager
  name: models-manager
spec:
  selector:
    matchLabels:
      app: models-manager
  template:
    metadata:
      labels:
        app: models-manager
    spec:
      containers:
        - image: sr2020/models-manager:TAG
          name: models-manager
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRESQL_HOST
              value: postgres-service
            - name: POSTGRESQL_DATABASE
              value: models
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POSTGRES_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: models-manager
spec:
  type: LoadBalancer
  selector:
    app: models-manager
  ports:
    - name: http
      port: 7007
      targetPort: 3000
