name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: bahmutov/npm-install@v1.1.0
      - run: npx lerna run coverage:test --concurrency=1 --stream -- --forbid-only
      - run: npx lerna run coverage:merge
      - run: yarn run coverage:coveralls
      - run: yarn run coverage:codecov
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: bahmutov/npm-install@v1.1.0
      - run: npx lerna run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: bahmutov/npm-install@v1.1.0
      - run: npx lerna run build
